- hosts: web
  tasks:
  - name: Install httpd
    yum:
     name: httpd
     state: latest
  - name: Start httpd
    systemd:
     name: httpd
     state: started
  - name: Enable httpd 
    systemd:
     name: httpd
     enabled: yes
     masked: no 
  - name: Download Templatest
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page246/freshshop.zip
      dest: /var/www/html/
  - name: install unzip
    yum:
      name: unzip
      state: latest
  
  - name: unzip file 
    unarchive:
      src: /var/www/html/freshshop.zip
      dest: /var/www/html
      remote_src: yes
  - name: move files
    shell: mv /var/www/html/freshshop/* /var/www/html

  